services:
  - type: web
    name: simple-hr-app
    env: python
    plan: free
    buildCommand: apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-kor && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SEED_DATABASE
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: simple-hr-db
          property: connectionString

databases:
  - name: simple-hr-db
    plan: free
